@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
Container(web, "Web App", "Java") {
  Component(controller, "Controller")
  Component(service, "Service")
}
Rel(controller, service, "Calls")
@enduml