@startuml
package "Ruby on Rails Service" {
  actor User
  component Router [
    Router
    Rails
  ]
  component Model [
    Model
    ActiveRecord
  ]
}

database PostgreSQL [
  Database
  PostgreSQL
]

User --> Router : Sends requests
Router --> Model : Uses
Model --> PostgreSQL : Reads/Writes
@enduml