@startuml
package "API Server" {
  actor Admin
  component Auth [
    Auth Module
    Flask
  ]
  component Data [
    Data Module
    Flask
  ]
}

database MongoDB [
  Database
  MongoDB
]

Admin --> Auth : Logs in
Auth --> Data : Grants access
Data --> MongoDB : Reads/Writes
@enduml