@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
Person(admin, "Administrator")
System(webApp, "Web Application")
System_Ext(emailService, "Email Service")
Rel(admin, webApp, "Manages")
Rel(webApp, emailService, "Sends notifications")
@enduml