@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Person(user, "User")
System_Boundary(system, "Notification System") {
  Container(ui, "UI", "Vue.js", "User interface")
  Container(service, "Notification Service", "Java", "Sends alerts")
  Container(db, "Database", "Oracle", "Stores preferences")
}
Rel(user, ui, "Configures alerts")
Rel(ui, service, "Sends config")
Rel(service, db, "Stores settings")
@enduml