"""
Provider System Test - Kroki Mermaid

Tests the krokimermaid provider using the provider system endpoint.
"""

from provider_test_helper import ProviderTestHelper
import json
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))


def load_test_cases(test_file: str = "test25.json") -> list:
    """Load test cases from test file"""
    script_dir = Path(__file__).parent
    test_path = script_dir / test_file

    if not test_path.exists():
        print(f"Error: Test file not found: {test_path}")
        return []

    try:
        with open(test_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Extract tests array
        if isinstance(data, dict):
            tests = data.get("mermaid_capability_tests", [])
        else:
            tests = data

        # Convert to expected format with LLM generation stage
        test_cases = []
        for i, test in enumerate(tests[:25], 1):
            test_cases.append(
                {
                    "id": test.get("id", i),
                    "description": test.get("description", f"Test {i}"),
                    "code": test.get("code", ""),  # Will be generated by LLM
                    "name": test.get("name", f"Test {i}"),
                }
            )

        return test_cases

    except Exception as e:
        print(f"Error loading tests: {e}")
        return []


def generate_and_render_diagram(helper, description, diagram_type, provider_id):
    """Generate code with LLM, then render with provider"""

    # Stage 1: Generate diagram code from description
    success, code, error = helper.generate_diagram_with_llm(prompt=description, diagram_type=diagram_type)

    if not success:
        return False, f"Generation failed: {error}", {}, ""

    # Stage 2: Render with provider
    success, content, metadata = helper.render_with_provider(
        code=code, diagram_type=diagram_type, provider_id=provider_id, output_format="svg"
    )

    return success, content if success else f"Render failed: {content}", metadata, code


class ProviderDiagramTest:
    """Test runner for provider diagram rendering"""

    def __init__(self, provider_id: str, diagram_type: str):
        self.provider_id = provider_id
        self.diagram_type = diagram_type
        self.helper = ProviderTestHelper()
        self.results = []

    def run_all_tests(self, test_cases: list):
        """Run all test cases"""
        print(f"\nTesting {len(test_cases)} diagrams with {self.provider_id}...")

        passed = 0
        failed = 0

        for i, test_case in enumerate(test_cases, 1):
            test_id = test_case["id"]
            description = test_case["description"]

            print(f"  [{i:2d}/{len(test_cases)}] {description[:60]}", end="")

            success, content, metadata, code = generate_and_render_diagram(
                self.helper, description, self.diagram_type, self.provider_id
            )

            if success:
                passed += 1
                print(" ✅")
                # Save SVG
                svg_file = Path("test_results_25/svg") / f"test_{test_id:03d}.svg"
                svg_file.parent.mkdir(parents=True, exist_ok=True)
                with open(svg_file, "w", encoding="utf-8") as f:
                    f.write(content)
            else:
                failed += 1
                print(" ❌")
                # Save error
                error_file = Path("test_results_25/errors") / f"test_{test_id:03d}_error.txt"
                error_file.parent.mkdir(parents=True, exist_ok=True)
                with open(error_file, "w", encoding="utf-8") as f:
                    f.write(f"Test {test_id}: {description}\n")
                    f.write(f"Error: {content}\n")

            self.results.append(
                {
                    "test_id": test_id,
                    "description": description,
                    "success": success,
                    "error": None if success else content,
                }
            )

        # Summary
        total = len(test_cases)
        success_rate = (passed / total * 100) if total > 0 else 0

        print(f"\n  Result: {passed}/{total} passed ({success_rate:.1f}%)")

        # Save validation results
        with open("test_results_25/errors/validation_results.json", "w") as f:
            json.dump(self.results, f, indent=2)

        return {
            "provider_id": self.provider_id,
            "diagram_type": self.diagram_type,
            "total": total,
            "passed": passed,
            "failed": failed,
            "success_rate": success_rate,
        }


def main():
    """Main entry point"""
    print("\n" + "=" * 80)
    print("Kroki Mermaid - Provider System Tests")
    print("=" * 80)

    test_cases = load_test_cases()
    if not test_cases:
        print("No test cases found!")
        return None

    tester = ProviderDiagramTest(provider_id="krokimermaid", diagram_type="mermaid")

    return tester.run_all_tests(test_cases)


if __name__ == "__main__":
    result = main()
    if result:
        sys.exit(0 if result["success_rate"] >= 50 else 1)
