"""
Master Test Runner - Execute all 7 provider test suites sequentially

This script runs all provider system tests in order:
1. llmd2test - D2 provider (d2v1)
2. llmmermaidtest - Mermaid provider (mermaidv1)
3. llmkrokid2test - Kroki D2 provider (krokid2)
4. llmkrokimermaidtest - Kroki Mermaid provider (krokimermaid)
5. llmkrokic4test - Kroki C4 provider (krokic4)
6. llmkrokiplantumtest - Kroki PlantUML provider (krokiplantuml)
7. llmkrokistructurizrtest - Kroki Structurizr provider (krokistructurizr)

Collects results from all providers and creates summary report.
"""

import json
import sys
import subprocess
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime

# Test configuration - maps test directory to (provider_id, diagram_type, test_file)
TEST_CONFIGS = [
    {
        'name': 'LLM D2',
        'dir': 'llmd2test',
        'provider_id': 'd2v1',
        'diagram_type': 'd2',
        'test_file': 'test25.json',
        'key': 'd2_capability_tests'
    },
    {
        'name': 'LLM Mermaid',
        'dir': 'llmmermaidtest',
        'provider_id': 'mermaidv1',
        'diagram_type': 'mermaid',
        'test_file': 'test25.json',
        'key': 'mermaid_capability_tests'
    },
    {
        'name': 'Kroki D2',
        'dir': 'llmkrokid2test',
        'provider_id': 'krokid2',
        'diagram_type': 'd2',
        'test_file': 'test25.json',
        'key': 'd2_capability_tests'
    },
    {
        'name': 'Kroki Mermaid',
        'dir': 'llmkrokimermaidtest',
        'provider_id': 'krokimermaid',
        'diagram_type': 'mermaid',
        'test_file': 'test25.json',
        'key': 'mermaid_capability_tests'
    },
    {
        'name': 'Kroki C4',
        'dir': 'llmkrokic4test',
        'provider_id': 'krokic4',
        'diagram_type': 'c4',
        'test_file': 'test25.json',
        'key': 'c4_capability_tests'
    },
    {
        'name': 'Kroki PlantUML',
        'dir': 'llmkrokiplantumtest',
        'provider_id': 'krokiplantuml',
        'diagram_type': 'plantuml',
        'test_file': 'test25.json',
        'key': 'plantuml_capability_tests'
    },
    {
        'name': 'Kroki Structurizr',
        'dir': 'llmkrokistructurizrtest',
        'provider_id': 'krokistructurizr',
        'diagram_type': 'structurizr',
        'test_file': 'test25.json',
        'key': 'structurizr_capability_tests'
    }
]


def create_test_script(config: Dict[str, Any], test_dir: Path) -> Path:
    """Create a provider test script for the given configuration"""

    script_path = test_dir / f"validate_all_25_{config['provider_id']}_provider.py"

    script_content = f'''"""
Provider System Test - {config['name']}

Tests the {config['provider_id']} provider using the provider system endpoint.
"""

import json
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from provider_test_helper import DiagramTestRunner, ProviderTestHelper


def load_test_cases(test_file: str = "{config['test_file']}") -> list:
    """Load test cases from test file"""
    script_dir = Path(__file__).parent
    test_path = script_dir / test_file

    if not test_path.exists():
        print(f"Error: Test file not found: {{test_path}}")
        return []

    try:
        with open(test_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Extract tests array
        if isinstance(data, dict):
            tests = data.get('{config['key']}', [])
        else:
            tests = data

        # Convert to expected format with LLM generation stage
        test_cases = []
        for i, test in enumerate(tests[:25], 1):
            test_cases.append({{
                'id': test.get('id', i),
                'description': test.get('description', f'Test {{i}}'),
                'code': test.get('code', ''),  # Will be generated by LLM
                'name': test.get('name', f'Test {{i}}')
            }})

        return test_cases

    except Exception as e:
        print(f"Error loading tests: {{e}}")
        return []


def generate_and_render_diagram(helper, description, diagram_type, provider_id):
    """Generate code with LLM, then render with provider"""

    # Stage 1: Generate diagram code from description
    success, code, error = helper.generate_diagram_with_llm(
        prompt=description,
        diagram_type=diagram_type
    )

    if not success:
        return False, f"Generation failed: {{error}}", {{}}, ""

    # Stage 2: Render with provider
    success, content, metadata = helper.render_with_provider(
        code=code,
        diagram_type=diagram_type,
        provider_id=provider_id,
        output_format='svg'
    )

    return success, content if success else f"Render failed: {{content}}", metadata, code


class ProviderDiagramTest:
    """Test runner for provider diagram rendering"""

    def __init__(self, provider_id: str, diagram_type: str):
        self.provider_id = provider_id
        self.diagram_type = diagram_type
        self.helper = ProviderTestHelper()
        self.results = []

    def run_all_tests(self, test_cases: list):
        """Run all test cases"""
        print(f"\\nTesting {{len(test_cases)}} diagrams with {{self.provider_id}}...")

        passed = 0
        failed = 0

        for i, test_case in enumerate(test_cases, 1):
            test_id = test_case['id']
            description = test_case['description']

            print(f"  [{{i:2d}}/{{len(test_cases)}}] {{description[:60]}}", end="")

            success, content, metadata, code = generate_and_render_diagram(
                self.helper,
                description,
                self.diagram_type,
                self.provider_id
            )

            if success:
                passed += 1
                print(" ✅")
                # Save SVG
                svg_file = Path("test_results_25/svg") / f"test_{{test_id:03d}}.svg"
                svg_file.parent.mkdir(parents=True, exist_ok=True)
                with open(svg_file, 'w', encoding='utf-8') as f:
                    f.write(content)
            else:
                failed += 1
                print(" ❌")
                # Save error
                error_file = Path("test_results_25/errors") / f"test_{{test_id:03d}}_error.txt"
                error_file.parent.mkdir(parents=True, exist_ok=True)
                with open(error_file, 'w', encoding='utf-8') as f:
                    f.write(f"Test {{test_id}}: {{description}}\\n")
                    f.write(f"Error: {{content}}\\n")

            self.results.append({{
                'test_id': test_id,
                'description': description,
                'success': success,
                'error': None if success else content
            }})

        # Summary
        total = len(test_cases)
        success_rate = (passed / total * 100) if total > 0 else 0

        print(f"\\n  Result: {{passed}}/{{total}} passed ({{success_rate:.1f}}%)")

        # Save validation results
        with open("test_results_25/errors/validation_results.json", 'w') as f:
            json.dump(self.results, f, indent=2)

        return {{
            'provider_id': self.provider_id,
            'diagram_type': self.diagram_type,
            'total': total,
            'passed': passed,
            'failed': failed,
            'success_rate': success_rate
        }}


def main():
    """Main entry point"""
    print("\\n" + "=" * 80)
    print(f"{config['name']} - Provider System Tests")
    print("=" * 80)

    test_cases = load_test_cases()
    if not test_cases:
        print("No test cases found!")
        return None

    tester = ProviderDiagramTest(
        provider_id="{config['provider_id']}",
        diagram_type="{config['diagram_type']}"
    )

    return tester.run_all_tests(test_cases)


if __name__ == "__main__":
    result = main()
    if result:
        sys.exit(0 if result['success_rate'] >= 50 else 1)
'''

    script_path.write_text(script_content, encoding='utf-8')
    return script_path


def run_test_suite(test_dir: Path, script_name: str) -> Dict[str, Any]:
    """Run a single test suite and return results"""

    script_path = test_dir / script_name

    if not script_path.exists():
        return {
            'success': False,
            'error': f'Script not found: {script_path}',
            'passed': 0,
            'failed': 25,
            'success_rate': 0
        }

    try:
        result = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=str(test_dir),
            capture_output=True,
            text=True,
            timeout=300
        )

        # Parse output for success rate
        lines = result.stdout.split('\n')
        for line in lines:
            if 'Result:' in line and 'passed' in line:
                return {
                    'success': True,
                    'output': result.stdout,
                    'error': result.stderr if result.returncode != 0 else None
                }

        return {
            'success': result.returncode == 0,
            'output': result.stdout,
            'error': result.stderr
        }

    except subprocess.TimeoutExpired:
        return {
            'success': False,
            'error': 'Test timeout (5 minutes exceeded)',
            'passed': 0,
            'failed': 25,
            'success_rate': 0
        }
    except Exception as e:
        return {
            'success': False,
            'error': str(e),
            'passed': 0,
            'failed': 25,
            'success_rate': 0
        }


def main():
    """Master test runner"""

    base_dir = Path(__file__).parent
    results = []

    print("\n" + "=" * 100)
    print("WHYSPER PROVIDER SYSTEM - FULL TEST SUITE")
    print("Running tests for all 7 diagram providers")
    print("=" * 100)

    start_time = datetime.now()

    for config in TEST_CONFIGS:
        test_dir = base_dir / config['dir']

        if not test_dir.exists():
            print(f"\n❌ Test directory not found: {test_dir}")
            results.append({
                'name': config['name'],
                'provider_id': config['provider_id'],
                'success': False,
                'error': 'Directory not found'
            })
            continue

        print(f"\n{'=' * 100}")
        print(f"Testing: {config['name']} ({config['provider_id']})")
        print(f"Location: {test_dir}")
        print(f"{'=' * 100}")

        # Create test script
        script_path = create_test_script(config, test_dir)
        print(f"Created test script: {script_path.name}")

        # Run test suite
        print(f"\nExecuting tests...")
        result = run_test_suite(test_dir, script_path.name)

        results.append({
            'name': config['name'],
            'provider_id': config['provider_id'],
            'diagram_type': config['diagram_type'],
            **result
        })

        # Print output
        if result.get('output'):
            print(result['output'][-500:] if len(result['output']) > 500 else result['output'])

        if result.get('error'):
            print(f"Error: {result['error'][:200]}")

    # Final summary
    print("\n" + "=" * 100)
    print("FINAL SUMMARY")
    print("=" * 100)

    for result in results:
        status = "✅" if result['success'] else "❌"
        print(f"{status} {result['name']:25} ({result.get('provider_id', 'N/A'):20})")

    elapsed = datetime.now() - start_time
    print(f"\nTotal execution time: {elapsed.total_seconds():.1f} seconds")
    print("=" * 100 + "\n")

    # Save results
    summary_file = base_dir / ".." / "PROVIDER_TEST_RESULTS.json"
    with open(summary_file, 'w') as f:
        json.dump({
            'timestamp': datetime.now().isoformat(),
            'total_suites': len(TEST_CONFIGS),
            'completed': sum(1 for r in results if r['success']),
            'results': results
        }, f, indent=2)

    print(f"Results saved to: {summary_file}")


if __name__ == "__main__":
    main()
